use_frameworks!

platform :ios, '9.0'

target 'GSMeow_Example' do
  pod 'GSMeow', :path => '../'

  target 'GSMeow_Tests' do
    inherit! :search_paths

    #pod 'Specta'
    #pod 'Expecta'
    #pod 'FBSnapshotTestCase'
    #pod 'Expecta+Snapshots'
  end
end
